# paper-plugin.yml
name: PurpurInsight
main: cancelcloud.PurpurInsightPlugin
version: "1.0.0"
api-version: "1.21"
load: STARTUP
authors:
  - Lukas
description: "Sammelt Server-Statistiken und sendet sie per Discord-Slash-Command."
commands:
  purpurinsight:
    description: "Setzt Discord-Channel-IDs"
    usage: "/purpurinsight <stats-channel|admin-channel> <id>"
    permission: purpurstats:discordsettings
